// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    mx_crash_sc
    (
        init => init
        upgrade => upgrade
        newGame => new_game
        submitBet => submit_bet
        endGame => end_game
        compute_prizes => compute_prizes
        claim => claim
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
