[package]
name = "mx-pay-for-user-sc-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.mx-pay-for-user-sc]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.59.0"
default-features = false
